GET http://localhost:5002/bruger/admin

###

GET http://localhost:5002/bruger/admin/5ee9ef934ff1205a9827f61e


###
POST http://localhost:5002/bruger/admin
Content-Type: application/json

{
    "brugernavn": "pedersen",
    "navn": "peder pedersen",
    "email": "p@y.dk",
    "password": "123456"
}

###

PUT http://localhost:5002/bruger/admin/5ee9ef934ff1205a9827f61e
Content-Type: application/json

{
    "brugernavn": "Timsen",
    "navn": "tim Timsen",
    "email": "t@t.dk",
    "password": "123456"
}
###

DELETE http://localhost:5002/bruger/admin

###

//mongodb+srv://Kirkemann:<password>@kirkemann-ah9zl.azure.mongodb.net/test
