GET http://localhost:5002/hunde

###

GET http://localhost:5002/hunde/5eea09ce29f7892e58025d54


###
POST http://localhost:5002/hunde/admin
Content-Type: application/json

{
    "name": "Laguso Jago",
    "hunderace": "Schæfer",
    "hundealder": "2"
}

###

DELETE http://localhost:5002/hunde/admin

###

PATCH  http://localhost:5002/hunde/admin/5ee9eff24ff1205a9827f620
Content-Type: application/json

{
    "name": "Aixa Randa",
    "hunderace": "Schæfer",
    "hundealder": "8 mdr"
}

###

GET http://localhost:5002/hunde/soeg/